server:
  port: 8080


kakao:
  authUrl: https://kauth.kakao.com/oauth/token
  userApiUrl: https://kapi.kakao.com/v2/user/me
  restapiKey: 6256af7a7e2f73f238d737407b4ddbcb
  redirectUrl: http://15.164.140.81:8080/callbacks

logging:
  level:
    com.blooming.modelServer: debug
    org.springframework.web: debug

#spring:
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 1234
#    url: jdbc:mysql:localhost:3306/test_db??useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul


#https://kauth.kakao.com/oauth/authorize?response_type=code&client_id=6256af7a7e2f73f238d737407b4ddbcb&redirect_uri=http://15.164.140.81:8080/callbacks
